//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebAJAX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vJobCandidateEducation
    {
        public int JobCandidateID { get; set; }
        public string Edu_Level { get; set; }
        public Nullable<System.DateTime> Edu_StartDate { get; set; }
        public Nullable<System.DateTime> Edu_EndDate { get; set; }
        public string Edu_Degree { get; set; }
        public string Edu_Major { get; set; }
        public string Edu_Minor { get; set; }
        public string Edu_GPA { get; set; }
        public string Edu_GPAScale { get; set; }
        public string Edu_School { get; set; }
        public string Edu_Loc_CountryRegion { get; set; }
        public string Edu_Loc_State { get; set; }
        public string Edu_Loc_City { get; set; }
    }
}
