//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebAJAX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSalesPersonSalesByFiscalYears
    {
        public Nullable<int> SalesPersonID { get; set; }
        public string FullName { get; set; }
        public string JobTitle { get; set; }
        public string SalesTerritory { get; set; }
        public Nullable<decimal> C2002 { get; set; }
        public Nullable<decimal> C2003 { get; set; }
        public Nullable<decimal> C2004 { get; set; }
    }
}
